#!/bin/bash

echo "======================================"
echo "Monitoring Stack Quick Start Guide"
echo "======================================"
echo ""

echo "1. Building and starting all services..."
docker-compose up -d --build

echo ""
echo "2. Waiting for services to be ready (30 seconds)..."
sleep 30

echo ""
echo "======================================"
echo "Services Status"
echo "======================================"
docker-compose ps

echo ""
echo "======================================"
echo "Access URLs"
echo "======================================"
echo "🌐 Gateway Service:       http://localhost:8080"
echo "📊 Grafana Dashboard:     http://localhost:3000 (admin/admin)"
echo "🔍 Jaeger Tracing:        http://localhost:16686"
echo "📈 Prometheus:            http://localhost:9095"
echo "📋 Loki:                  http://localhost:3100"
echo "💻 Node Exporter:         http://localhost:9100/metrics"
echo "🐳 cAdvisor:              http://localhost:8085"
echo ""
echo "======================================"
echo "Service Endpoints"
echo "======================================"
echo "Blog Service:             http://localhost:8081"
echo "Follower Service:         http://localhost:8082"
echo "Tour Service:             http://localhost:8083"
echo "Stakeholders Service:     http://localhost:8084"
echo ""
echo "======================================"
echo "Metrics Endpoints"
echo "======================================"
echo "Blog Service:             http://localhost:8081/metrics"
echo "Follower Service:         http://localhost:8082/metrics"
echo "Tour Service:             http://localhost:8083/metrics"
echo "Stakeholders Service:     http://localhost:8084/metrics"
echo "Gateway Service:          http://localhost:8080/metrics"
echo ""
echo "======================================"
echo "Quick Tests"
echo "======================================"
echo ""

echo "Testing Gateway health..."
curl -s http://localhost:8080/health && echo " ✅ Gateway is healthy" || echo " ❌ Gateway is not responding"

echo "Testing Blog Service health..."
curl -s http://localhost:8081/health && echo " ✅ Blog Service is healthy" || echo " ❌ Blog Service is not responding"

echo "Testing Prometheus..."
curl -s http://localhost:9095/-/healthy && echo " ✅ Prometheus is healthy" || echo " ❌ Prometheus is not responding"

echo "Testing Jaeger..."
curl -s http://localhost:16686/ > /dev/null && echo " ✅ Jaeger is responding" || echo " ❌ Jaeger is not responding"

echo ""
echo "======================================"
echo "View Logs"
echo "======================================"
echo "All services:          docker-compose logs -f"
echo "Specific service:      docker-compose logs -f blog-service"
echo "Monitoring services:   docker-compose logs -f prometheus loki jaeger"
echo ""
echo "======================================"
echo "Next Steps"
echo "======================================"
echo "1. Open Grafana at http://localhost:3000"
echo "2. Login with admin/admin"
echo "3. Go to 'Explore' to query logs and metrics"
echo "4. Go to Jaeger at http://localhost:16686 to view traces"
echo "5. Make some API calls to generate data"
echo ""
echo "Example API call to generate trace:"
echo "  curl http://localhost:8080/health"
echo ""
