// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: protos/follower.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Zahtev za dobijanje pratilaca
type GetFollowersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersRequest) Reset() {
	*x = GetFollowersRequest{}
	mi := &file_protos_follower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersRequest) ProtoMessage() {}

func (x *GetFollowersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_follower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersRequest.ProtoReflect.Descriptor instead.
func (*GetFollowersRequest) Descriptor() ([]byte, []int) {
	return file_protos_follower_proto_rawDescGZIP(), []int{0}
}

func (x *GetFollowersRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Jedan pratilac
type Follower struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Follower) Reset() {
	*x = Follower{}
	mi := &file_protos_follower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Follower) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Follower) ProtoMessage() {}

func (x *Follower) ProtoReflect() protoreflect.Message {
	mi := &file_protos_follower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Follower.ProtoReflect.Descriptor instead.
func (*Follower) Descriptor() ([]byte, []int) {
	return file_protos_follower_proto_rawDescGZIP(), []int{1}
}

func (x *Follower) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

// Odgovor sa listom pratilaca
type GetFollowersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Followers     []*Follower            `protobuf:"bytes,1,rep,name=followers,proto3" json:"followers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowersResponse) Reset() {
	*x = GetFollowersResponse{}
	mi := &file_protos_follower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowersResponse) ProtoMessage() {}

func (x *GetFollowersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_follower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowersResponse.ProtoReflect.Descriptor instead.
func (*GetFollowersResponse) Descriptor() ([]byte, []int) {
	return file_protos_follower_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowersResponse) GetFollowers() []*Follower {
	if x != nil {
		return x.Followers
	}
	return nil
}

var File_protos_follower_proto protoreflect.FileDescriptor

const file_protos_follower_proto_rawDesc = "" +
	"\n" +
	"\x15protos/follower.proto\x12\bfollower\".\n" +
	"\x13GetFollowersRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"#\n" +
	"\bFollower\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"H\n" +
	"\x14GetFollowersResponse\x120\n" +
	"\tfollowers\x18\x01 \x03(\v2\x12.follower.FollowerR\tfollowers2`\n" +
	"\x0fFollowerService\x12M\n" +
	"\fGetFollowers\x12\x1d.follower.GetFollowersRequest\x1a\x1e.follower.GetFollowersResponseB*Z(github.com/IvanNovakovic/SOA_Proj/protosb\x06proto3"

var (
	file_protos_follower_proto_rawDescOnce sync.Once
	file_protos_follower_proto_rawDescData []byte
)

func file_protos_follower_proto_rawDescGZIP() []byte {
	file_protos_follower_proto_rawDescOnce.Do(func() {
		file_protos_follower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_follower_proto_rawDesc), len(file_protos_follower_proto_rawDesc)))
	})
	return file_protos_follower_proto_rawDescData
}

var file_protos_follower_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_follower_proto_goTypes = []any{
	(*GetFollowersRequest)(nil),  // 0: follower.GetFollowersRequest
	(*Follower)(nil),             // 1: follower.Follower
	(*GetFollowersResponse)(nil), // 2: follower.GetFollowersResponse
}
var file_protos_follower_proto_depIdxs = []int32{
	1, // 0: follower.GetFollowersResponse.followers:type_name -> follower.Follower
	0, // 1: follower.FollowerService.GetFollowers:input_type -> follower.GetFollowersRequest
	2, // 2: follower.FollowerService.GetFollowers:output_type -> follower.GetFollowersResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_follower_proto_init() }
func file_protos_follower_proto_init() {
	if File_protos_follower_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_follower_proto_rawDesc), len(file_protos_follower_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_follower_proto_goTypes,
		DependencyIndexes: file_protos_follower_proto_depIdxs,
		MessageInfos:      file_protos_follower_proto_msgTypes,
	}.Build()
	File_protos_follower_proto = out.File
	file_protos_follower_proto_goTypes = nil
	file_protos_follower_proto_depIdxs = nil
}
