// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v4.25.1
// source: tour.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TourService_GetTourByID_FullMethodName      = "/tour.TourService/GetTourByID"
	TourService_GetToursByAuthor_FullMethodName = "/tour.TourService/GetToursByAuthor"
)

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tour service
type TourServiceClient interface {
	// Get tour by ID
	GetTourByID(ctx context.Context, in *GetTourByIDRequest, opts ...grpc.CallOption) (*GetTourByIDResponse, error)
	// Get tours by author
	GetToursByAuthor(ctx context.Context, in *GetToursByAuthorRequest, opts ...grpc.CallOption) (*GetToursByAuthorResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) GetTourByID(ctx context.Context, in *GetTourByIDRequest, opts ...grpc.CallOption) (*GetTourByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTourByIDResponse)
	err := c.cc.Invoke(ctx, TourService_GetTourByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetToursByAuthor(ctx context.Context, in *GetToursByAuthorRequest, opts ...grpc.CallOption) (*GetToursByAuthorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetToursByAuthorResponse)
	err := c.cc.Invoke(ctx, TourService_GetToursByAuthor_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility.
//
// Tour service
type TourServiceServer interface {
	// Get tour by ID
	GetTourByID(context.Context, *GetTourByIDRequest) (*GetTourByIDResponse, error)
	// Get tours by author
	GetToursByAuthor(context.Context, *GetToursByAuthorRequest) (*GetToursByAuthorResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTourServiceServer struct{}

func (UnimplementedTourServiceServer) GetTourByID(context.Context, *GetTourByIDRequest) (*GetTourByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTourByID not implemented")
}
func (UnimplementedTourServiceServer) GetToursByAuthor(context.Context, *GetToursByAuthorRequest) (*GetToursByAuthorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToursByAuthor not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}
func (UnimplementedTourServiceServer) testEmbeddedByValue()                     {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	// If the following call panics, it indicates UnimplementedTourServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_GetTourByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTourByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetTourByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetTourByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetTourByID(ctx, req.(*GetTourByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetToursByAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetToursByAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetToursByAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TourService_GetToursByAuthor_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetToursByAuthor(ctx, req.(*GetToursByAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTourByID",
			Handler:    _TourService_GetTourByID_Handler,
		},
		{
			MethodName: "GetToursByAuthor",
			Handler:    _TourService_GetToursByAuthor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour.proto",
}
