// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v4.25.1
// source: tour.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for getting tour by ID
type GetTourByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TourId        string                 `protobuf:"bytes,1,opt,name=tour_id,json=tourId,proto3" json:"tour_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIDRequest) Reset() {
	*x = GetTourByIDRequest{}
	mi := &file_tour_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIDRequest) ProtoMessage() {}

func (x *GetTourByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIDRequest.ProtoReflect.Descriptor instead.
func (*GetTourByIDRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{0}
}

func (x *GetTourByIDRequest) GetTourId() string {
	if x != nil {
		return x.TourId
	}
	return ""
}

// Request for getting tours by author
type GetToursByAuthorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthorId      string                 `protobuf:"bytes,1,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByAuthorRequest) Reset() {
	*x = GetToursByAuthorRequest{}
	mi := &file_tour_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByAuthorRequest) ProtoMessage() {}

func (x *GetToursByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetToursByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{1}
}

func (x *GetToursByAuthorRequest) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

// Transport duration information
type TransportDuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Walking       int32                  `protobuf:"varint,1,opt,name=walking,proto3" json:"walking,omitempty"` // minutes
	Biking        int32                  `protobuf:"varint,2,opt,name=biking,proto3" json:"biking,omitempty"`   // minutes
	Driving       int32                  `protobuf:"varint,3,opt,name=driving,proto3" json:"driving,omitempty"` // minutes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransportDuration) Reset() {
	*x = TransportDuration{}
	mi := &file_tour_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransportDuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransportDuration) ProtoMessage() {}

func (x *TransportDuration) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransportDuration.ProtoReflect.Descriptor instead.
func (*TransportDuration) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{2}
}

func (x *TransportDuration) GetWalking() int32 {
	if x != nil {
		return x.Walking
	}
	return 0
}

func (x *TransportDuration) GetBiking() int32 {
	if x != nil {
		return x.Biking
	}
	return 0
}

func (x *TransportDuration) GetDriving() int32 {
	if x != nil {
		return x.Driving
	}
	return 0
}

// Tour information
type Tour struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Difficulty    string                 `protobuf:"bytes,5,opt,name=difficulty,proto3" json:"difficulty,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	Price         float64                `protobuf:"fixed64,8,opt,name=price,proto3" json:"price,omitempty"`
	Distance      float64                `protobuf:"fixed64,9,opt,name=distance,proto3" json:"distance,omitempty"` // kilometers
	Durations     *TransportDuration     `protobuf:"bytes,10,opt,name=durations,proto3" json:"durations,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,11,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	ArchivedAt    string                 `protobuf:"bytes,12,opt,name=archived_at,json=archivedAt,proto3" json:"archived_at,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tour) Reset() {
	*x = Tour{}
	mi := &file_tour_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tour) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tour) ProtoMessage() {}

func (x *Tour) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tour.ProtoReflect.Descriptor instead.
func (*Tour) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{3}
}

func (x *Tour) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tour) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Tour) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tour) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Tour) GetDifficulty() string {
	if x != nil {
		return x.Difficulty
	}
	return ""
}

func (x *Tour) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Tour) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Tour) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Tour) GetDistance() float64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Tour) GetDurations() *TransportDuration {
	if x != nil {
		return x.Durations
	}
	return nil
}

func (x *Tour) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Tour) GetArchivedAt() string {
	if x != nil {
		return x.ArchivedAt
	}
	return ""
}

func (x *Tour) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// Response for getting tour by ID
type GetTourByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tour          *Tour                  `protobuf:"bytes,1,opt,name=tour,proto3" json:"tour,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTourByIDResponse) Reset() {
	*x = GetTourByIDResponse{}
	mi := &file_tour_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTourByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTourByIDResponse) ProtoMessage() {}

func (x *GetTourByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTourByIDResponse.ProtoReflect.Descriptor instead.
func (*GetTourByIDResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{4}
}

func (x *GetTourByIDResponse) GetTour() *Tour {
	if x != nil {
		return x.Tour
	}
	return nil
}

// Response for getting tours by author
type GetToursByAuthorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tours         []*Tour                `protobuf:"bytes,1,rep,name=tours,proto3" json:"tours,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetToursByAuthorResponse) Reset() {
	*x = GetToursByAuthorResponse{}
	mi := &file_tour_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetToursByAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetToursByAuthorResponse) ProtoMessage() {}

func (x *GetToursByAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tour_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetToursByAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetToursByAuthorResponse) Descriptor() ([]byte, []int) {
	return file_tour_proto_rawDescGZIP(), []int{5}
}

func (x *GetToursByAuthorResponse) GetTours() []*Tour {
	if x != nil {
		return x.Tours
	}
	return nil
}

var File_tour_proto protoreflect.FileDescriptor

const file_tour_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"tour.proto\x12\x04tour\"-\n" +
	"\x12GetTourByIDRequest\x12\x17\n" +
	"\atour_id\x18\x01 \x01(\tR\x06tourId\"6\n" +
	"\x17GetToursByAuthorRequest\x12\x1b\n" +
	"\tauthor_id\x18\x01 \x01(\tR\bauthorId\"_\n" +
	"\x11TransportDuration\x12\x18\n" +
	"\awalking\x18\x01 \x01(\x05R\awalking\x12\x16\n" +
	"\x06biking\x18\x02 \x01(\x05R\x06biking\x12\x18\n" +
	"\adriving\x18\x03 \x01(\x05R\adriving\"\x81\x03\n" +
	"\x04Tour\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"difficulty\x18\x05 \x01(\tR\n" +
	"difficulty\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x14\n" +
	"\x05price\x18\b \x01(\x01R\x05price\x12\x1a\n" +
	"\bdistance\x18\t \x01(\x01R\bdistance\x125\n" +
	"\tdurations\x18\n" +
	" \x01(\v2\x17.tour.TransportDurationR\tdurations\x12!\n" +
	"\fpublished_at\x18\v \x01(\tR\vpublishedAt\x12\x1f\n" +
	"\varchived_at\x18\f \x01(\tR\n" +
	"archivedAt\x12\x1d\n" +
	"\n" +
	"created_at\x18\r \x01(\tR\tcreatedAt\"5\n" +
	"\x13GetTourByIDResponse\x12\x1e\n" +
	"\x04tour\x18\x01 \x01(\v2\n" +
	".tour.TourR\x04tour\"<\n" +
	"\x18GetToursByAuthorResponse\x12 \n" +
	"\x05tours\x18\x01 \x03(\v2\n" +
	".tour.TourR\x05tours2\xa4\x01\n" +
	"\vTourService\x12B\n" +
	"\vGetTourByID\x12\x18.tour.GetTourByIDRequest\x1a\x19.tour.GetTourByIDResponse\x12Q\n" +
	"\x10GetToursByAuthor\x12\x1d.tour.GetToursByAuthorRequest\x1a\x1e.tour.GetToursByAuthorResponseB*Z(github.com/IvanNovakovic/SOA_Proj/protosb\x06proto3"

var (
	file_tour_proto_rawDescOnce sync.Once
	file_tour_proto_rawDescData []byte
)

func file_tour_proto_rawDescGZIP() []byte {
	file_tour_proto_rawDescOnce.Do(func() {
		file_tour_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)))
	})
	return file_tour_proto_rawDescData
}

var file_tour_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tour_proto_goTypes = []any{
	(*GetTourByIDRequest)(nil),       // 0: tour.GetTourByIDRequest
	(*GetToursByAuthorRequest)(nil),  // 1: tour.GetToursByAuthorRequest
	(*TransportDuration)(nil),        // 2: tour.TransportDuration
	(*Tour)(nil),                     // 3: tour.Tour
	(*GetTourByIDResponse)(nil),      // 4: tour.GetTourByIDResponse
	(*GetToursByAuthorResponse)(nil), // 5: tour.GetToursByAuthorResponse
}
var file_tour_proto_depIdxs = []int32{
	2, // 0: tour.Tour.durations:type_name -> tour.TransportDuration
	3, // 1: tour.GetTourByIDResponse.tour:type_name -> tour.Tour
	3, // 2: tour.GetToursByAuthorResponse.tours:type_name -> tour.Tour
	0, // 3: tour.TourService.GetTourByID:input_type -> tour.GetTourByIDRequest
	1, // 4: tour.TourService.GetToursByAuthor:input_type -> tour.GetToursByAuthorRequest
	4, // 5: tour.TourService.GetTourByID:output_type -> tour.GetTourByIDResponse
	5, // 6: tour.TourService.GetToursByAuthor:output_type -> tour.GetToursByAuthorResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_tour_proto_init() }
func file_tour_proto_init() {
	if File_tour_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tour_proto_rawDesc), len(file_tour_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tour_proto_goTypes,
		DependencyIndexes: file_tour_proto_depIdxs,
		MessageInfos:      file_tour_proto_msgTypes,
	}.Build()
	File_tour_proto = out.File
	file_tour_proto_goTypes = nil
	file_tour_proto_depIdxs = nil
}
